remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: ''
  - Intro to Tapis and The Command Line Interface:
    - Intro to Tapis(Agave): block3/tapis-intro
    - Intro to Tapis CLI: block3/tapis-cli
  - Intro to Systems:
    - Intro to Tapis Systems: block3/tapis-systems
  - Intro to Apps:
    - Intro to Apps: block4/apps
  - Intro to Jobs:
    - Intro to Tapis Jobs with Aloe: block4/jobs

theme: jekyll-theme-hacker